networks:
  mqtt-network:
    driver: bridge
services:
  mqtt-broker:
    container_name: smart-mqtt
    hostname: mqtt-broker
    image: smartboot/smart-mqtt:latest
    networks:
      mqtt-network: null
    environment:
      ENTERPRISE_ENABLE: true
#      BROKER_LOWMEMORY: true
      BROKER_MAXINFLIGHT: 256
    restart: always
    privileged: true
    security_opt:
      - no-new-privileges:true
    user: root:root
    ports:
      - 18083:18083
      - 1883:1883
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  mqtt-broker-2:
    container_name: smart-mqtt-2
    hostname: mqtt-broker-2
    image: smartboot/smart-mqtt:latest
    networks:
      mqtt-network: null
    environment:
      ENTERPRISE_ENABLE: false
      #      BROKER_LOWMEMORY: true
      BROKER_MAXINFLIGHT: 256
    restart: always
    privileged: true
    security_opt:
      - no-new-privileges:true
    user: root:root
    ports:
      - 18084:18083
      - 1884:1883
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

